// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rasp.Api.Data;

#nullable disable

namespace Rasp.Api.Migrations
{
    [DbContext(typeof(RaspDbContext))]
    [Migration("20260422105901_AddControleSelecaoPn")]
    partial class AddControleSelecaoPn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rasp.Api.Models.ContaCrRasp", b =>
                {
                    b.Property<int>("IdContaCr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_conta_cr");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContaCr"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("IdContaCr");

                    b.ToTable("conta_cr_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.ContaCrSubcontaRasp", b =>
                {
                    b.Property<int>("IdSubcontaCr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_subconta_cr");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSubcontaCr"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("BurdenCenter")
                        .HasColumnType("text")
                        .HasColumnName("burden_center");

                    b.Property<string>("CodigoSubconta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_subconta");

                    b.Property<string>("DescricaoSubconta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_subconta");

                    b.Property<int>("IdContaCr")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta_cr");

                    b.HasKey("IdSubcontaCr");

                    b.ToTable("conta_cr_subconta_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.EmpresaSelecaoRasp", b =>
                {
                    b.Property<int>("IdEmpresaSelecao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa_selecao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresaSelecao"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_empresa");

                    b.Property<string>("TipoEmpresa")
                        .HasColumnType("text")
                        .HasColumnName("tipo_empresa");

                    b.HasKey("IdEmpresaSelecao");

                    b.ToTable("empresa_selecao_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.FornecedorRasp", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fornecedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFornecedor"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Duns")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duns");

                    b.Property<int?>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("TipoFornecedor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_fornecedor");

                    b.HasKey("IdFornecedor");

                    b.ToTable("fornecedor_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.GmAliadoRasp", b =>
                {
                    b.Property<int>("IdGmAliadoRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_gm_aliado_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGmAliadoRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdGmAliadoRasp");

                    b.ToTable("gm_aliado_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.ImpactoClienteRasp", b =>
                {
                    b.Property<int>("IdImpactoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_impacto_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdImpactoCliente"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdImpactoCliente");

                    b.ToTable("impacto_cliente_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.ImpactoQualidadeRasp", b =>
                {
                    b.Property<int>("IdImpactoQualidadeRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_impacto_qualidade_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdImpactoQualidadeRasp"));

                    b.Property<short?>("CodigoOpcao")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_opcao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdImpactoQualidadeRasp");

                    b.ToTable("impacto_qualidade_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.IndiceOperacionalRasp", b =>
                {
                    b.Property<int>("IdIndiceOperacionalRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_indice_operacional_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIndiceOperacionalRasp"));

                    b.Property<short>("CodigoOpcao")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_opcao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("IdIndiceOperacionalRasp");

                    b.ToTable("indice_operacional_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.MaiorImpactoRasp", b =>
                {
                    b.Property<int>("IdMaiorImpactoRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_maior_impacto_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMaiorImpactoRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdMaiorImpactoRasp");

                    b.ToTable("maior_impacto_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.MajorRasp", b =>
                {
                    b.Property<int>("IdMajorRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_major_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMajorRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdMajorRasp");

                    b.ToTable("major_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.ModeloVeiculoRasp", b =>
                {
                    b.Property<int>("IdModeloVeiculoRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_modelo_veiculo_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdModeloVeiculoRasp"));

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_modelo");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdModeloVeiculoRasp");

                    b.ToTable("modelo_veiculo_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.OperadorSelecaoTerceiro", b =>
                {
                    b.Property<int>("IdOperadorSelecaoTerceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_operador_selecao_terceiro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOperadorSelecaoTerceiro"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inativacao");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("IdOperadorSelecaoTerceiro");

                    b.ToTable("operador_selecao_terceiro", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.OrigemFabricacaoRasp", b =>
                {
                    b.Property<int>("IdOrigemFabricacaoRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_origem_fabricacao_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrigemFabricacaoRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdOrigemFabricacaoRasp");

                    b.ToTable("origem_fabricacao_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.PerfilRasp", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_perfil");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("IdPerfil");

                    b.ToTable("perfil_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.PilotoRasp", b =>
                {
                    b.Property<int>("IdPilotoRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_piloto_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPilotoRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdPilotoRasp");

                    b.ToTable("piloto_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.PnRasp", b =>
                {
                    b.Property<int>("IdPn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pn");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPn"));

                    b.Property<string>("CodigoPn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_pn");

                    b.Property<string>("NomePeca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_peca");

                    b.HasKey("IdPn");

                    b.ToTable("pn_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.RaspAnotacao", b =>
                {
                    b.Property<int>("IdRaspAnotacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp_anotacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRaspAnotacao"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<int>("IdPerfilRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_perfil_rasp");

                    b.Property<int>("IdRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TextoAnotacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_anotacao");

                    b.Property<string>("TipoAnotacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_anotacao");

                    b.HasKey("IdRaspAnotacao");

                    b.ToTable("rasp_anotacao", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.RaspArquivo", b =>
                {
                    b.Property<int>("IdArquivoRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_arquivo_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArquivoRasp"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateOnly>("DataUpload")
                        .HasColumnType("date")
                        .HasColumnName("data_upload");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("IdRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp");

                    b.Property<int>("IdUsuarioUpload")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_upload");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_arquivo");

                    b.HasKey("IdArquivoRasp");

                    b.ToTable("rasp_arquivo", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.RaspBp", b =>
                {
                    b.Property<int>("IdRaspBp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp_bp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRaspBp"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ComoIdentificado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("como_identificado");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataBp")
                        .HasColumnType("date")
                        .HasColumnName("data_bp");

                    b.Property<TimeSpan>("HoraBp")
                        .HasColumnType("interval")
                        .HasColumnName("hora_bp");

                    b.Property<int>("IdRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp");

                    b.Property<string>("LocalCelula")
                        .HasColumnType("text")
                        .HasColumnName("local_celula");

                    b.Property<string>("TipoReferenciaBp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_referencia_bp");

                    b.Property<string>("Vin")
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.HasKey("IdRaspBp");

                    b.ToTable("rasp_bp");
                });

            modelBuilder.Entity("Rasp.Api.Models.RaspContencao", b =>
                {
                    b.Property<int>("IdRaspContencao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp_contencao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRaspContencao"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataHoraFimAtividade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahora_fim_atividade");

                    b.Property<DateTime?>("DataHoraInicioAtividade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahora_inicio_atividade");

                    b.Property<DateOnly?>("DataLoteVerificada")
                        .HasColumnType("date")
                        .HasColumnName("data_lote_verificado");

                    b.Property<DateOnly>("DataSelecao")
                        .HasColumnType("date")
                        .HasColumnName("data_selecao");

                    b.Property<decimal?>("HorasRetrabalho")
                        .HasColumnType("numeric")
                        .HasColumnName("horas_retrabalho");

                    b.Property<int?>("IdEmpresaSelecaoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa_selecao_rasp");

                    b.Property<int?>("IdOperadorSelecaoTerceiro")
                        .HasColumnType("integer")
                        .HasColumnName("id_operador_selecao_terceiro");

                    b.Property<int>("IdRaspPn")
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp_pn");

                    b.Property<int?>("IdTurnoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_turno_rasp");

                    b.Property<int?>("IdUsuarioExecucao")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_execucao");

                    b.Property<string>("NrScrap")
                        .HasColumnType("text")
                        .HasColumnName("nr_scrap");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<short?>("OrigemRegistro")
                        .HasColumnType("smallint")
                        .HasColumnName("origem_registro");

                    b.Property<int>("QuantidadeChecada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_checada");

                    b.Property<int?>("QuantidadeOk")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_ok");

                    b.Property<int?>("QuantidadeRejeitada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_rejeitada");

                    b.Property<int?>("QuantidadeRetrabalhada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_retrabalhada");

                    b.Property<int?>("QuantidadeVerificada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_verificada");

                    b.Property<string>("TipoAcao")
                        .HasColumnType("text")
                        .HasColumnName("tipo_acao");

                    b.HasKey("IdRaspContencao");

                    b.ToTable("rasp_contencao");
                });

            modelBuilder.Entity("Rasp.Api.Models.RaspEntity", b =>
                {
                    b.Property<int>("IdRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRasp"));

                    b.Property<short?>("AnoRasp")
                        .HasColumnType("smallint")
                        .HasColumnName("ano_rasp");

                    b.Property<bool?>("AprovadoLg")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovado_lg");

                    b.Property<DateTime?>("BpDatahora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bp_datahora");

                    b.Property<string>("BpSerie")
                        .HasColumnType("text")
                        .HasColumnName("bp_serie");

                    b.Property<string>("BpTexto")
                        .HasColumnType("text")
                        .HasColumnName("bp_texto");

                    b.Property<string>("BreakpointCodigo")
                        .HasColumnType("text")
                        .HasColumnName("breakpoint_codigo");

                    b.Property<DateTime?>("BreakpointDatahora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("breakpoint_datahora");

                    b.Property<string>("BreakpointTexto")
                        .HasColumnType("text")
                        .HasColumnName("breakpoint_texto");

                    b.Property<string>("CampanhaNumero")
                        .HasColumnType("text")
                        .HasColumnName("campanha_numero");

                    b.Property<DateOnly?>("DataContato")
                        .HasColumnType("date")
                        .HasColumnName("data_contato");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly?>("DataFechamento")
                        .HasColumnType("date")
                        .HasColumnName("data_fechamento");

                    b.Property<string>("DescricaoProblema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_problema");

                    b.Property<bool?>("EmitiuPrr")
                        .HasColumnType("boolean")
                        .HasColumnName("emitiu_prr");

                    b.Property<bool?>("GeraPrr")
                        .HasColumnType("boolean")
                        .HasColumnName("gera_prr");

                    b.Property<TimeOnly>("HoraCriacao")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_criacao");

                    b.Property<int?>("IdAnalista")
                        .HasColumnType("integer")
                        .HasColumnName("id_analista");

                    b.Property<int?>("IdAnalistaMt")
                        .HasColumnType("integer")
                        .HasColumnName("id_analista_mt");

                    b.Property<int?>("IdAprovadorFt")
                        .HasColumnType("integer")
                        .HasColumnName("id_aprovador_ft");

                    b.Property<int?>("IdAprovadorLg")
                        .HasColumnType("integer")
                        .HasColumnName("id_aprovador_lg");

                    b.Property<int?>("IdContaCrRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta_cr_rasp");

                    b.Property<int?>("IdContaCrSubcontaRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta_cr_subconta_rasp");

                    b.Property<int?>("IdEmpresaSelecaoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa_selecao_rasp");

                    b.Property<int>("IdFornecedorRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_fornecedor_rasp");

                    b.Property<int?>("IdGmAliadoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_gm_aliado_rasp");

                    b.Property<int?>("IdImpactoClienteRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_impacto_cliente_rasp");

                    b.Property<int?>("IdImpactoQualidadeRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_impacto_qualidade_rasp");

                    b.Property<int?>("IdIndiceOperacionalRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_indice_operacional_rasp");

                    b.Property<int?>("IdMaiorImpactoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_maior_impacto_rasp");

                    b.Property<int?>("IdMajorRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_major_rasp");

                    b.Property<int?>("IdModeloVeiculoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_modelo_veiculo_rasp");

                    b.Property<int?>("IdOrigemFabricacaoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_origem_fabricacao_rasp");

                    b.Property<int?>("IdPerfilRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_perfil_rasp");

                    b.Property<int?>("IdPilotoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_piloto_rasp");

                    b.Property<int?>("IdSetorRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_setor_rasp");

                    b.Property<int?>("IdSppsClassificacaoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_spps_classificacao_rasp");

                    b.Property<int?>("IdSppsStatusRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_spps_status_rasp");

                    b.Property<int>("IdStatusRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_status_rasp");

                    b.Property<int?>("IdTurnoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_turno_rasp");

                    b.Property<bool?>("IniciativaFornecedor")
                        .HasColumnType("boolean")
                        .HasColumnName("iniciativa_fornecedor");

                    b.Property<bool>("IsRascunho")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rascunho");

                    b.Property<bool?>("IsReversao")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reversao");

                    b.Property<bool?>("IsSafety")
                        .HasColumnType("boolean")
                        .HasColumnName("is_safety");

                    b.Property<bool?>("IsSupplierAlert")
                        .HasColumnType("boolean")
                        .HasColumnName("is_supplier_alert");

                    b.Property<string>("NomeContato")
                        .HasColumnType("text")
                        .HasColumnName("nome_contato");

                    b.Property<string>("NumeroRasp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_rasp");

                    b.Property<string>("ObservacaoGeral")
                        .HasColumnType("text")
                        .HasColumnName("observacao_geral");

                    b.Property<short>("PercentualCompletude")
                        .HasColumnType("smallint")
                        .HasColumnName("percentual_completude");

                    b.Property<string>("Procedencia")
                        .HasColumnType("text")
                        .HasColumnName("procedencia");

                    b.Property<string>("RdNumero")
                        .HasColumnType("text")
                        .HasColumnName("rd_numero");

                    b.Property<bool?>("Reversao")
                        .HasColumnType("boolean")
                        .HasColumnName("reversao");

                    b.Property<bool?>("Safety")
                        .HasColumnType("boolean")
                        .HasColumnName("safety");

                    b.Property<string>("SppsNumero")
                        .HasColumnType("text")
                        .HasColumnName("spps_numero");

                    b.Property<bool?>("SupplierAlert")
                        .HasColumnType("boolean")
                        .HasColumnName("supplier_alert");

                    b.HasKey("IdRasp");

                    b.ToTable("rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.RaspPnEntity", b =>
                {
                    b.Property<int>("IdRaspPn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp_pn");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRaspPn"));

                    b.Property<DateTime?>("DataHoraEntradaSelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahora_entrada_selecao");

                    b.Property<DateTime?>("DataHoraQhd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahora_qhd");

                    b.Property<DateTime?>("DataHoraRemocaoTrava")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahora_remocao_trava");

                    b.Property<DateTime?>("DataHoraSaidaSelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahora_saida_selecao");

                    b.Property<DateTime?>("DataHoraSolicitacaoTrava")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahora_solicitacao_trava");

                    b.Property<DateTime?>("DataLoteInicial")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lote_inicial");

                    b.Property<string>("Duns")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duns");

                    b.Property<bool>("EmContencao")
                        .HasColumnType("boolean")
                        .HasColumnName("em_contencao");

                    b.Property<bool>("EntrouSelecao")
                        .HasColumnType("boolean")
                        .HasColumnName("entrou_selecao");

                    b.Property<int>("IdRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_rasp");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.Property<string>("Pn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pn");

                    b.Property<bool>("QhdAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("qhd_ativo");

                    b.Property<int>("QuantidadeChecada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_checada");

                    b.Property<int>("QuantidadeRejeitada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_rejeitada");

                    b.Property<int>("QuantidadeSuspeita")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_suspeita");

                    b.Property<short>("StatusSelecao")
                        .HasColumnType("smallint")
                        .HasColumnName("status_selecao");

                    b.Property<bool>("TravaAtiva")
                        .HasColumnType("boolean")
                        .HasColumnName("trava_ativa");

                    b.HasKey("IdRaspPn");

                    b.ToTable("rasp_pn", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.SetorRasp", b =>
                {
                    b.Property<int>("IdSetorRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_setor_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSetorRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdSetorRasp");

                    b.ToTable("setor_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.SppsClassificacaoRasp", b =>
                {
                    b.Property<int>("IdSppsClassificacaoRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_spps_classificacao_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSppsClassificacaoRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdSppsClassificacaoRasp");

                    b.ToTable("spps_classificacao_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.SppsStatusRasp", b =>
                {
                    b.Property<int>("IdSppsStatusRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_spps_status_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSppsStatusRasp"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<bool>("ContaParaPrazo")
                        .HasColumnType("boolean")
                        .HasColumnName("conta_para_prazo");

                    b.Property<bool>("EhFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_final");

                    b.Property<string>("NomeStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_status");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdSppsStatusRasp");

                    b.ToTable("spps_status_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.StatusRasp", b =>
                {
                    b.Property<int>("IdStatusRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_status_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStatusRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemFluxo")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_fluxo");

                    b.HasKey("IdStatusRasp");

                    b.ToTable("status_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.TurnoRasp", b =>
                {
                    b.Property<int>("IdTurnoRasp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_turno_rasp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTurnoRasp"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<short>("OrdemExibicao")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdTurnoRasp");

                    b.ToTable("turno_rasp", (string)null);
                });

            modelBuilder.Entity("Rasp.Api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gmin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gmin");

                    b.Property<int?>("IdPerfil")
                        .HasColumnType("integer")
                        .HasColumnName("id_perfil");

                    b.Property<int?>("IdTurnoRasp")
                        .HasColumnType("integer")
                        .HasColumnName("id_turno_rasp");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
